### ISSUE TITLE
Mongorito v3

### ISSUE THREAD

**Issue by vadimdemedes** [vadimdemedes/mongorito#138]
Hey everyone, Mongorito's been quiet for a long time now, but it deserves more attention that it has right now. I've been looking into library's code, repository issues and pull requests and decided to roll out a v2 of Mongorito in the coming weeks. 

Current state of Mongorito's codebase is not what I want it to be. It is bloated and it does not fit a variety of use cases. Here's a plan of improvements to build into a new major release. Note, that it will not be compatible with the current version, so a migration guide will be provided.
#### 1. No more singleton Mongorito instance

Instead of this:

``` js
const mongorito = require('mongorito');
mongorito.connect(url);
```

We're going to have something like this:

``` js
const mongorito = require('mongorito');
const db = mongorito.create(); // or
const db = new mongorito.Database(); // or
const db = new mongorito.Db(); // or
const db = mongorito.connect();
```

Singleton `Mongorito` object leads to a dirty code in Mongorito's codebase and makes the whole library less flexible. It makes connecting to multiple databases inconvenient.
#### 2. Drop .extend() and go ES6 only

After the next release, `.extend()` is no longer to be included in the core. To define a model, you will have to use ES6 classes.
#### 3. Registration of models

Since singletons are to be discontinued (see point nr. 1) and the only way to define a model is through an ES6 class (see previous point), there has to be a way to connect models to databases. In Mongoose you have `db.model()` method and we'll have something similar:

``` js
db.register(Post);
db.register(Comment);
```

I think this is simple enough and easy to understand what it's for.
#### 4. Export only necessary properties from the native driver

Currently, Mongorito exports every property with a few exceptions from the native driver. I don't think it serves any purpose, as what's most often needed is just `ObjectId`.
#### 5. Drop generator support in hooks

Since you can define hooks explicitly for `before`, `after` and `around` events, there's no need for flow control via generator functions. Next release will only support "regular" functions and functions that return `Promise`s (async functions).

Note, you will still be able to use code like this:

``` js
const post = yield Post.find();
```

This change is related only to defining hooks inside models.
#### 6. Use query building library like mquery

I think it would be wise to not reinvent the wheel and wrap some query building library (like mquery) to handle the queries in Mongorito. Those libraries usually have good command coverage, so I think most people's needs would be satisfied.

**Feel free to discuss and add anything to this list.**

**Comment by mathieug** [comment]
Nice roadmap, do you plan to push the branch v2 anytime soon?

**Comment by vinhtq** [comment]
Awesome! Mongorito fits perfect in Adonisjs syntax also! Thank for your nice working!

**Comment by vdemedes** [comment]
It's a WIP, will push the branch asap.

**Comment by vdemedes** [comment]
@mathieug v3 branch pushed up - https://github.com/vdemedes/mongorito/tree/v3.

**Comment by vdemedes** [comment]
Big update! Everything except is **done**:

- Export only necessary properties from the native driver
- Per-model and per-database hooks
- Plugin system
- New readme

**Comment by vdemedes** [comment]
**Update**! Mongorito v3 is ready and now only needs a new readme.

**Comment by nervgh** [comment]
Could I operate with mongorito' predefined fields like
```
created_at -> createdAt
updated_at -> updatedAt
```
camel cased fields in v3?

**Comment by nervgh** [comment]
Great job! :smile_cat:  When do you plan release v3? Do you release alpha/beta of v3?

**Comment by vdemedes** [comment]
@nervgh I want to make those field names configurable, I feel like both of those are good defaults.

> When do you plan release v3?

I'd rather not give any ETAs. I still want to implement saving of models inside models (that's what MongoDB basically is, nested documents :D) And don't forget the most annoying part - documentation.

> Do you release alpha/beta of v3?

For now, you can use `v3` branch instead of the package published on npm. Make sure to report any bugs, greatly appreciated! Before the major bump, I'll definitely release v3 with `alpha` or `beta` tag.

**Comment by nervgh** [comment]
> For now, you can use `v3` branch instead of the package published on npm

Exactly! I will install **mongorito** from branch `v3`. Thanks! :smiley: 

>  I still want to implement saving of models inside models (that's what MongoDB basically is, nested documents :D)

I think my project [recursive-iterator](https://github.com/nervgh/recursive-iterator) may be helpful for your purposes. Using it you could iterate through nested structures [very simple](https://github.com/nervgh/recursive-iterator#example-es6).

**Comment by nervgh** [comment]
@vdemedes It looks like I cannot install `v3` from branch because:
1. package.json [does not allow](https://github.com/vdemedes/mongorito/blob/v3/package.json#L30) it
2. [`lib` vs `src`](https://github.com/vdemedes/mongorito/blob/v3/index.js#L3)

**Comment by vdemedes** [comment]
@nervgh package.json allows it, why would you think it wasn't? What error are you getting?

**Comment by vdemedes** [comment]
OH, I'm not committing `lib` folder, so it's empty when installed...

**Comment by vdemedes** [comment]
I think I should get rid of unsupported ES6 syntax and remove babel transpilation of the source.

**Comment by vdemedes** [comment]
@nervgh Removed babel, now the install should go fine!

**Comment by nervgh** [comment]
@vdemedes thanks!

I need `Query.in(key, array)` method. How I could run it? It looks like the `in` method does not exists anymore or it has been deprecated.
What do you think about of next syntax?
```js
let queryBuilder = new MyModel.Query(); // Query has been exported as the static property of Model
queryBuilder.in(key, array);
queryBuilder.sort(key, direction);
// etc
let result = yield queryBuilder.exec();
```

**Comment by vdemedes** [comment]
@nervgh Sorry for late response, here's how you can use `.in()`:

```js
const posts = await Post.where('title').in(['Bad title', 'Great title']).find();
```

**Comment by niallobrien** [comment]
Great ORM and I'' excited to see continued work on this project.

**Comment by vdemedes** [comment]
@niallobrien Thank you, means a lot to me! I updated the docs, so v3 release is going to be (hopefully) released soon.

**Comment by vinhtq** [comment]
Can I suggest a migration feature?

**Comment by vdemedes** [comment]
@vinhtq Could you elaborate what you mean exactly?

**Comment by niallobrien** [comment]
I'd love to see an adapter for Feathers.js

**Comment by vinhtq** [comment]
@vdemedes Something looks like this: https://github.com/derickbailey/migroose

**Comment by zaaack** [comment]
What about static configure method for each model? It's useful when creating indexes or adding global hooks.

**Comment by zaaack** [comment]
Since ensureIndex is declared, should mongorito add a new createIndexes method too?   http://stackoverflow.com/questions/25968592/difference-between-createindex-and-ensureindex-in-java-using-mongodb

**Comment by vadimdemedes** [comment]
@vinhtq It's out of scope of this library, it's just a database abstraction.

> What about static configure method for each model? It's useful when creating indexes or adding global hooks.
@zaaack Might be a good idea (v2 had it), will see what can be done here. Thanks!

> Since ensureIndex is declared, should mongorito V3 add a new createIndexes method too?
@zaaack From what I've read on SO link you referenced, `ensureIndex` is deprecated. I think I'll just remove `ensureIndex` and use `createIndex` instead. Thanks for pointing this out!

**Comment by zaaack** [comment]
@vadimdemedes Actually insert, remove, update are all declared too by something like insertOne and insertMany...  http://mongodb.github.io/node-mongodb-native/2.2/api/Collection.html#insert

**Comment by zaaack** [comment]
The static configure method, I find an implementation by v3's plugin system,I love that! Maybe can add some built-in plugins.

```js
db.use(function staticConfigure(model) {
  model.connection().then(conn => {
    // static configure
    model.configure && model.configure()
  })
})
```

**Comment by TongChia** [comment]
great work !~
But I worry It does not support aggregate queries and map-reduce.

It makes it possible not to guarantee complex business logic.

**Comment by zaaack** [comment]
Allow sort with array arguments, hash option can't guarantee the order of multi-fields, new driver and mquery support array sort arguments.

https://github.com/aheckmann/mquery/blob/master/lib/mquery.js#L1214

**Comment by niallobrien** [comment]
Any plans to move to async/await?

**Comment by vadimdemedes** [comment]
@niallobrien Mongorito v3 (and legacy v2) already returns promises for all methods where async operations happen. You can use async/await on any of them.

**Comment by vadimdemedes** [comment]
Since v3 is out, closing this issue.
