### ISSUE TITLE
[docs] Keep connection alive? 

### ISSUE THREAD

**Issue by Gratiandev** [vadimdemedes/mongorito#153]
Hello, I am writing a basic API server using your great library. I'm not very experienced and I'm wondering whether I should keep single database connection alive for the whole life of the process or open and close connections on every client request? If I keep it alive, what will happen if the database gets disconnected? ``mongoose`` has built-in re-connection feature, I haven't found anything similar in ``mongorito``. Will there any events be fired? Please explain! Thanks!

**Comment by vadimdemedes** [comment]
Yes, you only keep initialize Mongorito once when your app starts up.

> mongoose has built-in re-connection feature, I haven't found anything similar in mongorito. Will there any events be fired? Please explain! Thanks!

Just got down to implementing it, and found out that `mongodb` driver reconnects automatically. Wonderful!
