### ISSUE TITLE
How do turn arrays into JSON ?

### ISSUE THREAD

**Issue by du5rte** [vadimdemedes/mongorito#164]
Hi, first of all great library this answers a lot of my needs 👍

So to retrieve the data from a query that returns a single document I've understood you use `get()` or `toJSON()`
```js
async function(id) {
  const user = await User.findById(new ObjectId(id))

  return user.toJSON() // {"name": "John", "age": 27 ...}
}
```

To retrieve the data from a query that returns a list of documents I thought you'd do the same
```js
async function() {
  const users = await User.find()
  
  return users.toJSON()// [{"name": "John", "age": 27 ...}, {"name": "David", "age": 23 ...}]
}
```

but it returns an error 
```
Error: TypeError: users.toJSON is not a function
```

So how do you retrieve data from a list of documents?

Cheers,
Eddie

**Comment by du5rte** [comment]
Nevermind I've figured it out, maybe this should be added to docs.

```js
async function() {
  const users = await User.find()
  
  return users.map(user => user.toJSON()) // [{"name": "John", "age": 27 ...}, {"name": "David", "age": 23 ...}]
}
```

**Comment by zaaack** [comment]
@du5rte Actually if you are using `JSON.stringify` to serialize data to response, you don't need to call toJSON manually, `JSON.stringify` would call this for you.

**Comment by vadimdemedes** [comment]
@zaaack is right, in case you need to serialize data.

But if you want to just get document's fields:

```js
const user = await User.find({...});
user.get('email'); //=> test@gmail.com
```
