### ISSUE TITLE
Single Collection Inheritance

### ISSUE THREAD

**Issue by secretfader** [vadimdemedes/mongorito#17]
I need to store several models in the same collection, and be able to discriminate between objects, based on the specific model that I'm querying. Like so:

``` javascript
var Account = Mongorito.Model.extend({
   collection: 'accounts',
   configure: function () {
      this.before('save', 'validate');
   },
   validate: function * (next) {
      // some basic validations for all models inheriting from Account
      yield next;
   }
});

var User = Account.extend({
   configure: function () {
      this.before('save', 'validateEmailExists');
   },
   validateEmailExists: function * (next) {
      // validate that email exists
      yield next;
   }
});
```

Validations, like `validateEmailExists` on the `User` model, should be fired after the `Account` validations pass.

And when I call `Account.find()`, I will expect to see all models stored in the `accounts` collection for a given query, regardless of the model that was instantiated and saved to create this record. However, if I call `User.find()`, I should only return records that were created by the `User` model.

Mongoose [handles this by using a discriminator function](https://github.com/LearnBoost/mongoose/issues/2399), which is mostly undocumented and I think, rough to use. Is there a simple way to handle this use case in Mongorito?

**Comment by vdemedes** [comment]
Interesting issue, I must say. I think it can be implemented without any special functions, but still like Mongoose does it, using `__t` field in documents. But I am not sure, if developers would like it.

**Comment by nicholaswyoung** [comment]
It's a pretty common thing to do in MongoDB, actually. So I'm guessing most developers would at least like to have the option.

The biggest pain point in my app(s) has always been getting the data structure (or ORM/ODM) right on the first try. Having to switch out the data storage/mapping layer is a huge pain in the ass. And I can't think of something more frustrating than starting with one ODM only to realize it doesn't support all of the common practices of the database behind it. 

So, yep, I'm totally in favor of having something like this in Mongorito. Is there an API you have in mind? If so, I can work up a pull request.

**Comment by nicholaswyoung** [comment]
@vdemedes Any idea how I might be able to implement this in user-land even if the feature doesn't make it into Mongorito core?

**Comment by vdemedes** [comment]
I'd say set `__t` field in `setDefaults` method, which equals to your model name. That way, each document created by that particular model will have __t field and later use `.where('__t', 'User')` to fetch those documents.

**Comment by nicholaswyoung** [comment]
Would there be a way to extend the Query for that model so it always grabs that ```__t``` field automatically when instantiated?
