### ISSUE TITLE
how to find records with date, anything like whereDate?

### ISSUE THREAD

**Issue by webreinvent** [vadimdemedes/mongorito#172]
Guys,

I am storing ```created_at``` in ```YYYY-MM-DD HH:MM:SS``` format and I am receiving date in ```YYYY-MM-DD``` format. I need to run a where condition. Can you please assist me?

Thanks

**Comment by vadimdemedes** [comment]
So you are not storing dates as instances of `Date`?

**Comment by webreinvent** [comment]
@vadimdemedes no, I am storing it in ```YYYY-MM-DD HH:MM:SS``` format

**Comment by vadimdemedes** [comment]
In that case, regex is your best bet to match the `YYYY-MM-DD` part.
