### ISSUE TITLE
Returning an object from an async function will run `find`

### ISSUE THREAD

**Issue by Alex-iFactory** [vadimdemedes/mongorito#176]
Since the new API has the method `then`, when returning a model from an async function, node will try to run that then function without a query.

eg:

```
const test = async () => {
    let model = await Model.findById([id]);

    // return model
    return model;
};

const testagain = async () => {
    // await test
    await test (); // this will fail, throwing "Expected `query` to be object or undefined, got function"
};
```

**Comment by Alex-iFactory** [comment]
Removing the function `then` in `query.js` fixes this.

**Comment by vadimdemedes** [comment]
The code above is clearly invalid, it's an error.

**Comment by vadimdemedes** [comment]
Good point, removing it right away.

**Comment by vadimdemedes** [comment]
`3.0.1` is out with a fix, thanks!
