### ISSUE TITLE
How to use inherited(?) mquery findOneAndUpdate method

### ISSUE THREAD

**Issue by adieuadieu** [vadimdemedes/mongorito#203]
Hello @vadimdemedes. Thanks for this neat project!

How can I use the `findOneAndUpdate()` method that's inherited from mquery?

Or, is this not possible because `findOneAndUpdate` doesn't fall into the category of a query-condition methods (like `all()` or `and()`, but rather a query-method ..method (like `find()`, `distinct()`), which must be implemented in mongorito itself?

I can do it like this, but it seems like abuse (and the result is not an instance of the Mongorito model):

```js
const blah = MyFancyModel.findOneAndUpdate(
  { something: 'somevalue' },
  { somethingElse: 'some other value' },
  { upsert: true }
)

const result = await MyFancyModel.query('findOneAndUpdate', blah.query)
```

or more specifically:

```js
const result = await MyFancyModel.query('findOneAndUpdate', [
  [
    'findOneAndUpdate',
    [
      { something: 'somevalue' },
      { somethingElse: 'some other value' },
      { upsert: true }
    ],
  ]
])

**Comment by vadimdemedes** [comment]
Hey, thanks! To use this method it has to be added to these 2 files:

- https://github.com/vadimdemedes/mongorito/blob/master/lib/query-methods.js
- https://github.com/vadimdemedes/mongorito/blob/master/lib/query.js

Would you be interested in making a PR for it?

**Comment by adieuadieu** [comment]
Thanks @vadimdemedes! I'll raise a PR.

**Comment by adieuadieu** [comment]
@vadimdemedes I've raised PR #210 for this.
