### ISSUE TITLE
mongo:// url schema not supported

### ISSUE THREAD

**Issue by srohde** [vadimdemedes/mongorito#3]
When you try to connect with the mongo url schema (mongo://staff.mongohq.com:10000]/foo) instead of a host it does not work.
See last paragraph here http://garyrafferty.com/2011/12/06/Using-NodeJS-ExpressJS-and-MongoHQ-on-Heroku.html

var Mongolian = require('mongolian');
var server, db;

if(process.env.MONGOHQ_URL) {
  db = new Mongolian(process.env.MONGOHQ_URL);
} else {
  server = new Mongolian;
  db = server.db('your_db_name');
}

**Comment by azappa** [comment]
I've got a mongoURL like this:
`export MONGO_URL=mongodb://username:password@host:port/db-name`
but when I run my app I got an error like this: 
```net.js:901
      throw new RangeError('port should be > 0 and < 65536: ' + port);
            ^
RangeError: port should be > 0 and < 65536: 0
```

In my js file:

```
var Mongorito = require('mongorito');
var Model = Mongorito.Model;

Mongorito.connect(process.env.MONGO_URL);
```

**Comment by vdemedes** [comment]
Seems like it's a problem with monk, not Mongorito. Can you show how MONGO_URL looks like?

**Comment by azappa** [comment]
Ok, I make it work! Probably the password I've used contains strange symbols (like !s).
Thank you anyway!
